


spring:
  main-redis:
    host: localhost
    port: 6379
    timeout: 6000
    password:
    pool:
      max-active: 10
      max-idle: 5
      max-wait: 2
      min-idle: 1
  lesser-redis:
      host: localhost
      port: 6333
      timeout: 6000
      password:
      pool:
         max-active: 10
         max-idle: 5
         max-wait: 2
         min-idle: 1